
<source>
  @type forward
  port 24224
</source>

<match myapp.logs>
  @type cloudwatch_logs

  region us-east-2
  log_group_name eden27-fluend
  log_stream_name QuickFull-A9ETo4

  auto_create_stream true
  auto_create_group true
</match>